[project]
name = "vultr-py"
version = "0.1.0"
description = ""
authors = [
    {name = "Siyoung September",email = "loldruger@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp (>=3.11.11,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
